### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by hongminglin08** [ttgeng233/UniAV#1]
If I do not comment lines 107 and 108 of UniAV-main/libs/utils/train_utils.py, the first two errors in the picture will appear, and the last error will appear after I comment both, how can I fix it?

![BPA)_3 E7RDWIOAS%DGET%1](https://github.com/ttgeng233/UniAV/assets/52478955/c4efe088-11d6-4ffb-b035-3cae1656ed74)

![5MBF%992(~I4KI}7Z {(Q41](https://github.com/ttgeng233/UniAV/assets/52478955/cd28e106-09c9-4655-8368-a3aa34ffd000)

**Comment by ttgeng233** [comment]
Sorry for that. I reviewed my code, and there is no error reported if I don't comment L108-109. Is there anything changed in your code?

**Comment by hongminglin08** [comment]
> Sorry for that. I reviewed my code, and there is no error reported if I don't comment L108-109. Is there anything changed in your code?

Yes, I comment the part of train.py that relates to “rank”, and the following commands are used during training: “python train.py./configs/multi_task_anet_unav_dcase.yaml --output reproduce --tasks 3 --num_train_epochs 5”, does that matter? What if I don't want to use multiple Gpus?

**Comment by ttgeng233** [comment]
You can use the bellow command to use 1 GPU under distributed training mode: 
CUDA_VISIBLE_DEVICES=0 MASTER_ADDR=localhost WORLD_SIZE=1 RANK=0 python -m torch.distributed.launch --master_port 29600 --nproc_per_node=1 train.py ./configs/multi_task_anet_unav_dcase.yaml --output reproduce  --tasks 1-2-3 --num_train_epochs 5

**Comment by hongminglin08** [comment]
solved. thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tiantian ***@***.***&gt;; 
发送时间: 2024年6月12日(星期三) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ttgeng233/UniAV] code error (Issue #1)














 
You can use the bellow command to use 1 GPU under distributed training mode:
 CUDA_VISIBLE_DEVICES=0 MASTER_ADDR=localhost WORLD_SIZE=1 RANK=0 python -m torch.distributed.launch --master_port 29600 --nproc_per_node=1 train.py ./configs/multi_task_anet_unav_dcase.yaml --output reproduce  --tasks 1-2-3 --num_train_epochs 5

**Comment by ttgeng233** [comment]
No worries!
